version: '3.1'

services:
  app:
    build: otp-app:latest
    container_name: otp-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    environment:
      - environment=dockerized
    networks:
      - otp-management
  db:
    image: postgres:17.2-alpine
    container_name: otp-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - otp-management

  redis:
    image: redis:7.4.2 
    container_name: otp-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/otp_redis_data
    networks:
      - otp-management

volumes:
  pgdata:
  redis-data:

networks:
  otp-management:
    driver: bridge