version: '3.1'

services:
  db:
    image: postgres:17.2-alpine
    container_name: user-db
    restart: always
    environment:
    # TODO: if it going to deployed on k8s ADD it to configMAp
      POSTGRES_USER: agi
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: user_management 
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: