server:
  host: 'localhost'

# TODO: change it to 'memory'
database: 'postgres'

postgres:
  user: "agi"
  pass: "pass"
  db: "user_management"
  host: "localhost"
  port: 5432

otpCacheReservedKey: "otp"

cache:
  host: "localhost"
  port: 6379
  password: "" # TODO: implement later using env variables
  db: 0

requestTimeoutInSeconds: 10

autoMigrationEnable: true
