server:
  host: ''

database: 'postgres'

postgres:
  user: "agi"
  pass: "pass"
  db: "user_management"
  host: "db"
  port: 5432

otpCacheReservedKey: "otp"

cache:
  host: "redis"
  port: 6379
  password: "" # TODO: implement later using env variables
  db: 0

autoMigrationEnable: true
